version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'django2'
       MYSQL_ROOT_PASSWORD: 'MyPassword'
    volumes:
      - volume-mysql:/var/lib/mysql
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  volume-mysql: